name: Intelligent PR Summary

# on:
#pull_request:
#  types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  generate-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate PR Summary
        id: summary
        run: |
          # Create temporary markdown file
          SUMMARY_FILE="pr_summary.md"

          echo "## 📝 PR Change Analysis" >> $SUMMARY_FILE
          echo "### 🗒 Commit Messages" >> $SUMMARY_FILE
          git log --pretty=format:"- **%h**: %s (%an)" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} >> $SUMMARY_FILE

          echo -e "\n### 📊 File Statistics" >> $SUMMARY_FILE
          git diff --stat ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} >> $SUMMARY_FILE

          echo -e "\n### 📂 Changed Files" >> $SUMMARY_FILE
          git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | awk '{print "- " $0}' >> $SUMMARY_FILE

          echo -e "\n### 🔍 Notable Changes" >> $SUMMARY_FILE
          git diff --diff-filter=AM ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} -- '*.js' '*.ts' '*.py' '*.go' | wc -l | awk '{print "- Detected code changes in " $1 " relevant files"}' >> $SUMMARY_FILE

          # Store content for later use
          SUMMARY_CONTENT=$(cat $SUMMARY_FILE)
          echo "SUMMARY_CONTENT<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post Summary as Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.summary.outputs.SUMMARY_CONTENT }}

            ### ℹ️ How to Read This
            - Commit messages show development history
            - File stats reveal change scope
            - Filters highlight code files (*.js, *.ts, *.py, *.go)
          edit-mode: replace
