name: Auto PR Description

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  generate-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR Diff
        id: git-diff
        run: |
          git diff "${{ github.event.pull_request.base.sha }}".."${{ github.event.pull_request.head.sha }}" > changes.diff
          DIFF=$(cat changes.diff | jq -sR)
          echo "DIFF=$DIFF" >> $GITHUB_OUTPUT

      - name: Create PR Summary Comment
        uses: actions/github-script@v6
        with:
          script: |
            const diffContent = `${{ steps.git-diff.outputs.DIFF }}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "GitHub's AI will automatically show a summary option above this comment.\n\n" +
                    "For reference, here are the changed files:\n" +
                    diffContent.split('\n').filter(line => line.startsWith('+++') || line.startsWith('---')).join('\n')
            });
