name: Auto PR Description

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  generate-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR Diff
        id: git-diff
        run: |
          git diff "${{ github.event.pull_request.base.sha }}".."${{ github.event.pull_request.head.sha }}" > changes.diff
          echo "DIFF<<EOF" >> $GITHUB_OUTPUT
          cat changes.diff >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create PR Summary Comment
        uses: actions/github-script@v6
        with:
          script: |
            try {
              // Get raw diff output
              const diffContent = `${{ steps.git-diff.outputs.DIFF }}`;
              
              // Extract just the changed files list
              const changedFiles = diffContent.split('\n')
                .filter(line => line.startsWith('+++ b/') || line.startsWith('--- a/'))
                .map(line => line.replace('+++ b/', '').replace('--- a/', ''))
                .filter((value, index, self) => self.indexOf(value) === index);
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: "GitHub's AI will automatically show a summary option above this comment.\n\n" +
                      "### Changed Files\n" +
                      changedFiles.map(file => `- ${file}`).join('\n')
              });
            } catch (error) {
              core.error("Failed to create comment: " + error.message);
              // Fallback to simple comment if parsing fails
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: "GitHub's AI summary will appear above this comment."
              });
            }
