name: AI PR Summary with Groq

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  generate-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR Diff
        id: git-diff
        run: |
          git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} > diff.txt
          head -c 8000 diff.txt > trimmed_diff.txt
          DIFF_CONTENT=$(cat trimmed_diff.txt | jq -Rs .)
          echo "DIFF_CONTENT=$DIFF_CONTENT" >> $GITHUB_ENV

      - name: Generate Summary via Groq
        id: groq-summary
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          echo "Preparing JSON payload..."

          REQUEST=$(jq -n \
            --arg model "mixtral-8x7b-32768" \
            --arg system_content "You are a senior developer analyzing GitHub PRs. Provide: 1) Purpose (15 words max), 2) Key changes (bullets), 3) Impact." \
            --arg user_content "$DIFF_CONTENT" \
            '{
              model: $model,
              messages: [
                { role: "system", content: $system_content },
                { role: "user", content: $user_content }
              ],
              temperature: 0.2,
              max_tokens: 300
            }'
          )

          echo "Calling Groq API..."
          RESPONSE=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $GROQ_API_KEY" \
            -d "$REQUEST" \
            https://api.groq.com/openai/v1/chat/completions)

          echo "Raw Groq response:"
          echo "$RESPONSE"

          SUMMARY=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // "⚠️ Groq response was empty or invalid."')

          # Set output
          echo "SUMMARY<<EOF" >> $GITHUB_OUTPUT
          echo "### 🚀 Groq-Powered PR Analysis" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post summary
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.groq-summary.outputs.SUMMARY }}
          edit-mode: replace
