name: AI PR Summary with Mistral
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  generate-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR Diff
        id: git-diff
        run: |
          git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} > diff.txt
          echo "DIFF=$(cat diff.txt | jq -sR)" >> $GITHUB_OUTPUT

      - name: Generate Summary via Mistral API
        env:
          DIFF: ${{ steps.git-diff.outputs.DIFF }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: |
          SUMMARY=$(curl -s https://api.mistral.ai/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $MISTRAL_API_KEY" \
            -d '{
              "model": "mistral-medium-latest",
              "messages": [
                {
                  "role": "user",
                  "content": "Analyze this Git diff and create a concise PR summary with: 1) Main purpose (1 sentence), 2) Key changes (3 bullet points max), 3) Potential impact. Diff: '"$DIFF"'"
                }
              ],
              "temperature": 0.3
            }' | jq -r '.choices[0].message.content')

          echo "SUMMARY<<EOF" >> $GITHUB_OUTPUT
          echo "### 🤖 Mistral-Powered PR Analysis" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post summary
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.generate-summary.outputs.SUMMARY }}
          edit-mode: replace
