name: AI PR Summary with Mistral

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  summarize-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get diff
        id: diff
        run: |
          DIFF=$(git diff -U3 --ignore-all-space --ignore-blank-lines "${{ github.event.pull_request.base.sha }}" "${{ github.event.pull_request.head.sha }}" | head -c 6000)

          if [[ -z "$DIFF" || ${#DIFF} -lt 20 ]]; then
            echo "skip_summary=true" >> $GITHUB_OUTPUT
          else
            echo "skip_summary=false" >> $GITHUB_OUTPUT
            echo "$DIFF" > pr.diff
          fi

      - name: Generate summary with Mistral
        if: steps.diff.outputs.skip_summary == 'false'
        id: summary
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: |
          DIFF_CONTENT=$(cat pr.diff)

          PROMPT=$(cat <<EOF
          Analyze these code changes for a GitHub pull request and provide:
          1. **Purpose**: One sentence describing the main goal
          2. **Changes**: 3-5 specific technical modifications
          3. **Impact**: Potential effects on the system

          Diff:
          $DIFF_CONTENT
          EOF
          )

          REQUEST_JSON=$(jq -n \
            --arg prompt "$PROMPT" \
            '{
              model: "mistral-medium-latest",
              messages: [
                {
                  role: "system",
                  content: "You are a senior engineer analyzing GitHub PRs. Respond with clean markdown using only the requested sections."
                },
                {
                  role: "user",
                  content: $prompt
                }
              ],
              temperature: 0.2,
              max_tokens: 600
            }')

          RESPONSE=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $MISTRAL_API_KEY" \
            -d "$REQUEST_JSON" \
            https://api.mistral.ai/v1/chat/completions)

          echo "Raw API Response: $RESPONSE"

          SUMMARY=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')

          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "### 🤖 AI-Powered PR Analysis" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Detect affected areas and reviewers
        id: reviewers
        run: |
          set -euo pipefail

          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          REVIEWERS=""

          if echo "$FILES" | grep -q "^backend/"; then
            REVIEWERS="$REVIEWERS\n🧠 Review requested from: @nectar-soft/backend-team"
          fi

          if echo "$FILES" | grep -q "^frontend/"; then
            REVIEWERS="$REVIEWERS\n🎨 Review requested from: @nectar-soft/frontend-team"
          fi

          if echo "$FILES" | grep -q "^.github/workflows/"; then
            REVIEWERS="$REVIEWERS\n⚙️ Workflow updated. Consider notifying DevOps."
          fi

          echo "reviewers<<EOF" >> $GITHUB_OUTPUT
          echo -e "$REVIEWERS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment summary
        if: steps.diff.outputs.skip_summary == 'false'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.summary.outputs.summary }}


            ${{ steps.reviewers.outputs.reviewers }}
            _Generated using Mistral AI_

      - name: Skip comment
        if: steps.diff.outputs.skip_summary == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🤖 AI summary skipped: No significant code changes detected in this PR.
