name: AI PR Summary with Mistral
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  generate-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get and prepare diff
        id: prepare-diff
        run: |
          # Get unified diff with 5 lines of context
          RAW_DIFF=$(git diff -U5 ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})

          # Clean diff and convert to single line
          CLEAN_DIFF=$(echo "$RAW_DIFF" | 
          grep -v '^diff --git' |
          grep -v '^index ' |
          grep -v '^+++ ' |
          grep -v '^--- ' |
          tr '\n' ' ' |
          sed 's/"/\\"/g' |
          head -c 6000)

          # Store as environment variable (safe for multi-line content)
          echo "CLEAN_DIFF=\"$CLEAN_DIFF\"" >> $GITHUB_ENV

          # Create safe outputs
          echo "diff_length=${#CLEAN_DIFF}" >> $GITHUB_OUTPUT
          echo "diff_sample=$(echo "$CLEAN_DIFF" | head -c 100)" >> $GITHUB_OUTPUT

      - name: Generate summary
        id: generate-summary
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          DIFF_CONTENT: ${{ env.DIFF_CONTENT }}
        run: |
          # Debug output
          echo "Diff length: ${#DIFF_CONTENT} chars"
          echo "Sample: ${DIFF_CONTENT:0:100}..."

          # Prepare the API request
          REQUEST_JSON=$(jq -n \
            --arg diff "$DIFF_CONTENT" \
            --arg model "mistral-medium-latest" \
            '{
              model: $model,
              messages: [
                {
                  role: "system",
                  content: "You are a senior developer analyzing GitHub PRs. Provide: 1) Main purpose (15 words max), 2) 3 key changes (bullet points), 3) Potential impact. Never include code."
                },
                {
                  role: "user",
                  content: ("Analyze these changes: " + $diff)
                }
              ],
              temperature: 0.3,
              max_tokens: 500
            }')

          # Call Mistral API
          RESPONSE=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $MISTRAL_API_KEY" \
            -d "$REQUEST_JSON" \
            https://api.mistral.ai/v1/chat/completions)

          # Extract and set output
          SUMMARY=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
          echo "summary=$SUMMARY" >> $GITHUB_OUTPUT

      - name: Post summary comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### 🤖 Automated PR Analysis
            ${{ steps.generate-summary.outputs.summary }}

            _Generated at $(date -u +'%Y-%m-%d %H:%M UTC')_
          edit-mode: replace
