name: Auto PR Description

on:
  pull_request:
    types: [opened, synchronize]
permissions:
  contents: read
  pull-requests: write
jobs:
  generate-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR Diff
        id: git-diff
        run: |
          git diff "${{ github.event.pull_request.base.sha }}".."${{ github.event.pull_request.head.sha }}" > changes.diff
          DIFF=$(cat changes.diff | jq -sR)
          echo "DIFF=$DIFF" >> $GITHUB_OUTPUT

      - name: Call DeepSeek API
        id: deepseek
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          DIFF_CONTENT: ${{ steps.git-diff.outputs.DIFF }}
        run: |
          PAYLOAD=$(jq -n --arg diff "$DIFF_CONTENT" '
            {
              model: "deepseek-chat",
              messages: [
                {
                  role: "user",
                  content: "Summarize these code changes for a PR description:\n\n\($diff)"
                }
              ]
            }
          ')

          echo "$PAYLOAD"
          echo "$DIFF_CONTENT"
          echo "$DEEPSEEK_API_KEY"
          RESPONSE=$(curl -s -X POST "https://api.deepseek.com/v1/chat/completions" \
            -H "Authorization: Bearer $DEEPSEEK_API_KEY" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"
          )
          echo "API Response: $RESPONSE"
          SUMMARY=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
          echo "summary=$SUMMARY" >> $GITHUB_OUTPUT

      - name: Create or update PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### AI-Generated PR Summary

            ${{ steps.deepseek.outputs.summary }}
          edit-mode: replace
